### ISSUE TITLE
Write "how to build" manual please

### ISSUE THREAD

**Issue by Roman-Blinkov** [voronov-maxim/OdataToEntity#1]
Hi! Thank you for nice library!
I tried to build project in visual studio and in command prompt - no luck.
To produce attached build logs

[build-log-OdataToEntity.Test.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718918/build-log-OdataToEntity.Test.sln.txt)
[build-log-OdataToEntity.Wcf.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718917/build-log-OdataToEntity.Wcf.sln.txt)
[build-log-OdataToEntityCore.Asp.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718919/build-log-OdataToEntityCore.Asp.sln.txt)
[build-log-OdataToEntityCore.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718921/build-log-OdataToEntityCore.sln.txt)
[build-log-OdataToEntityCore.Test.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718920/build-log-OdataToEntityCore.Test.sln.txt)
[build-log-OdataToEntity.AspClient.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718924/build-log-OdataToEntity.AspClient.sln.txt)
[build-log-OdataToEntity.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718923/build-log-OdataToEntity.sln.txt)
[build-log-OdataToEntity.Test.Linq2Db.sln.txt](https://github.com/voronov-maxim/OdataToEntity/files/718922/build-log-OdataToEntity.Test.Linq2Db.sln.txt)

 I used command line:

C:\Src\OdataToEntity\sln>`for /f %f in ('dir *.sln /b') do msbuild %f > build-log-%f.txt
`

**Comment by voronov-maxim** [comment]
Install dotnet core sdk 1.1 https://www.microsoft.com/net/core#windowscmdversion 1.0.0-preview2-1-003177
1) Directory OdataToEntity run from command line
dotnet restore --no-cache
dotnet build
2) Directory OdataToEntity.EfCore
dotnet restore --no-cache
dotnet build

or install Visual Studio 2015 update 3 https://www.microsoft.com/net/core#windowsvs2015from command line should build always

**Comment by Roman-Blinkov** [comment]
I have .net sdk installed
![image](https://cloud.githubusercontent.com/assets/2073691/22144574/e4367ee8-df06-11e6-894f-5b15c35e72a4.png)
I have both Visual Studio 2015 and Visual Studio 2017 installed
Also I tried to build from vs2015 msbuild command prompt - fails
(logs from my prev message generated from 2017 command prompt)

**Comment by Roman-Blinkov** [comment]
Write something like this https://github.com/dotnet/corefxlab/blob/master/scripts/build.ps1 please

**Comment by voronov-maxim** [comment]
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md#how-do-i-work-with-projectjson-and-csproj-on-the-same-machine

{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}

when released VS 2017 i will porting from json to csproj

**Comment by voronov-maxim** [comment]
porting from json to csproj
