### ISSUE TITLE
It is not clear how to parametrize DbContext creation with DbContextOptions<TContext> ?

### ISSUE THREAD

**Issue by rpokrovskij** [voronov-maxim/OdataToEntity#10]
What I see from this code fragment:
```
//Create adapter data access, where OrderEf6Context your DbContext
var dataAdapter = new OeEf6DataAdapter<OrderEf6Context>();
//Build OData Edm Model
EdmModel edmModel = dataAdapter.BuildEdmModelFromEf6Model();
```

is that OrderEf6Context will be instantiated somewhere in OdataToEntity internals. But what if I need to pass my DbContextOptions<TContext> to it? (Case of not empty constructor)

**Comment by voronov-maxim** [comment]
inherit from OeEf6DataAdapter class and override CreateDataContext method

**Comment by rpokrovskij** [comment]
Thank you.

BTW I understand why but still it looks like legacy architecture when  CreateDataContext returns object instead of instance of DbContext type (generic type parameter of OeEfCoreDataAdapter). Please do not become angry on me. Just think you are interesting in your lib users opinion.

**Comment by voronov-maxim** [comment]
CreateDataContext return context for Ef6, Ef Core, Linq2Db
