### ISSUE TITLE
Explain WcfService sample

### ISSUE THREAD

**Issue by rpokrovskij** [voronov-maxim/OdataToEntity#11]
Please write several words about [WcfService ](https://github.com/voronov-maxim/OdataToEntity/tree/master/test/OdataToEntity.Wcf/OdataToEntity.WcfService) 

It so differ from "standard" EntityFrameworkDataService that I can't get it should work. 

What is the reason for this service:

    [ServiceContract]
    public interface IOrderDb
    {
        [OperationContract]
        void Init();
        [OperationContract]
        void Reset();
    }

**Comment by voronov-maxim** [comment]
this uses in test, init - initialize database, reset - clear database
