### ISSUE TITLE
ODataUnrecognizedPathException: Resource not found for the segment 'DimCustomer'.

### ISSUE THREAD

**Issue by elffikk** [voronov-maxim/OdataToEntity#12]
hi,
I am trying to expose a entity framework core dbset (connected to sql server) as odata.
I modified example from tests but got an error:
  
_An unhandled exception occurred while processing the request.

ODataUnrecognizedPathException: Resource not found for the segment 'DimCustomer'.
Microsoft.OData.UriParser.ODataPathParser.CreateDynamicPathSegment(ODataPathSegment previous, string identifier, string parenthesisExpression)
(see details attached)_
[odata05.zip](https://github.com/voronov-maxim/OdataToEntity/files/1317959/odata05.zip)
[odata-error.txt](https://github.com/voronov-maxim/OdataToEntity/files/1317960/odata-error.txt)

I used the database from this article https://www.codeproject.com/Articles/658912/Create-First-OLAP-Cube-in-SQL-Server-Analysis-Serv

**If possible, please provide a complete example with entity framework core in a simple controller (e.g. so I can secure it with Authorize attribute or a custom attribute)**

**Comment by voronov-maxim** [comment]
Query should be in plural
http://localhost:40348/odata/DimCustomers
not in single
http://localhost:40348/odata/DimCustomer (wrong)

**Comment by voronov-maxim** [comment]
Hi @elffikk 
complete example with entity framework core in a simple controller
test\OdataToEntity.Test.Asp\OdataToEntity.Test.AspMvcServer
