### ISSUE TITLE
Is there a way to ignore properties on objects (join tables)?

### ISSUE THREAD

**Issue by stodolos** [voronov-maxim/OdataToEntity#13]
Hi,

I am receiving the following error, b/c a join table doesn't have an explicit key, but rather a composite key.

> InvalidOperationException: The entity type 'RolePermissionSet' requires a primary key to be defined.

I know I could add an explicit key, and then change my composite key into a unique constraint, but I figured I'd check for other scenarios that I don't really want to be a part of my OData middleware.

Thanks!

Chris

**Comment by voronov-maxim** [comment]
Hi @stodolos,
'RolePermissionSet'  is this database view (stored procedure) that doesn't have a composite key?

OdataToEnity support [table with composition key](https://github.com/voronov-maxim/OdataToEntity/blob/dcd7f344f16bdf26d09587d53841b53d3c26ed6f/test/OdataToEntity.Test/Model/Order.cs#L24), [test composite key](https://github.com/voronov-maxim/OdataToEntity/blob/dcd7f344f16bdf26d09587d53841b53d3c26ed6f/test/OdataToEntity.Test/Common/SelectTest.cs#L646)

**Comment by stodolos** [comment]
It's a join/link table that looks like so:

public class RolePermissionSet
{
    public long RoleId { get; set; }
    public long PermissionSetId { get; set; }

	public virtual Role Role { get; set; }
	public virtual PermissionSet PermissionSet { get; set; }
}

**Comment by voronov-maxim** [comment]
Try [Many-to-many relationships](https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/)

**Comment by stodolos** [comment]
I am using that, and do have a key defined in an IEntityTypeConfiguration class:

`builder.HasKey(x => new { x.RoleId, x.PermissionSetId });`

**Comment by stodolos** [comment]
Why did you close this?  I am doing what you suggested already.  The problem is that in the code, it's explicitly looking for an "Id" column, or a [TableName]Id column.  It's not looking for a column that is the  key (whether it be composite or not).

**Comment by voronov-maxim** [comment]
If you using fluent api, instead BuildEdmModel must use extension method in Ef 6 BuildEdmModelFromEf6Model, in Ef core BuildEdmModelFromEfCoreModel.

Example in README.md "Build OData Edm Model".
