### ISSUE TITLE
Update NuGet packages

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#15]
I haven't had a chance to give this library a spin just yet, but initial impressions from looking at the code and tests looks very promising.

It appears this library supports the new .NET Core 2.1 that Microsoft's library currently [does not](https://github.com/OData/WebApi/issues/1447), along with `$apply` support (which is also currently [unsupported](https://github.com/OData/WebApi/issues/1221)).  I've always been looking for something a little lighter weight that `Microsoft.AspNetCore.OData` and this might just be it.

A few questions:
- I appears the NuGet packages haven't been updated in 2 months.  Could you push a new release soon?  It looks like support for `$apply` and query cache would be [included](https://github.com/voronov-maxim/OdataToEntity/commits/master) in the next release.
- Is it possible to apply restrictions to the query at runtime with this library (ex. do not allow a user to `$expand` deeply unless they have permission)?  Something like [this](https://blogs.msdn.microsoft.com/webdev/2013/02/06/protect-your-queryable-api-with-the-validation-feature-in-asp-net-web-api-odata/).
- Looking at [SelectTest](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test/Common/SelectTest.cs) it looks like most of my use cases are already supported (nested select/expand, various operators like `contains`, `startswith`, `any`, etc).  Do you know of any areas that currently lack support?

Btw I've created a few javascript libraries around OData, including [odata-query](https://github.com/techniq/odata-query) and [react-odata](https://github.com/techniq/react-odata) that you may be interested in.  `odata-query` provides a simple object-based syntax similar to MongoDB and js-data's query structure (making it easier to build queries as building the OData query string dynamically with it's nested structure can be challenging otherwise).

**Comment by voronov-maxim** [comment]
[nuget netcoreapp2.1](https://www.nuget.org/packages/OdataToEntity/1.5.0)

**Comment by voronov-maxim** [comment]
Hi @techniq
> s it possible to apply restrictions to the query at runtime with this library (ex. do not allow a user to $expand deeply unless they have permission)? Something like this.

Can use OeRequestHeaders.SetNavigationNextLink(true) that suppress expand and generates @odata.nextLink.


> Do you know of any areas that currently lack support?

Dont support filter navigation properties one-one relationship by design.
Like _OrderItems?$expand=Order($filter=Name eq 'Order 1')_
