### ISSUE TITLE
Cache does not consider function within $filter

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#18]
If caching is left enabled, calling a query that uses `contains`, `startswith`, etc will return the same result set of the initial call.

For example, calling:
```
http://localhost:5000/odata/Departments?$top=10&$filter=contains(Name,'Admin')
```
and then calling
```
http://localhost:5000/odata/Departments?$top=10&$filter=contains(Name,'Information')
```
will return the same result as the first.  If you stop and restart the server, the second result set is then returned (but calling the first will now return the second's, etc)

As a workaround, I've disabled the cache in the data adapter
```c#
public class CommonDbDataAdapter : OeEfCoreDataAdapter<CommonDbContext>
    {
        public CommonDbDataAdapter(DbContextOptions options) : base(options, new OeQueryCache(false)) {}
    }
}
```

**Comment by voronov-maxim** [comment]
Thanks, this is it was [misspelling](https://github.com/voronov-maxim/OdataToEntity/commit/254f79cae96fee5e1dcd8e1c4a482c004b7bbfba#diff-e311c6dc488ea457c7a87ff73ab31c2dL184)
