### ISSUE TITLE
Unable to build: Missing MaterializationContext

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#19]
After pulling the latest changes, I am unable to build due to a missing [MaterializationContext](https://github.com/voronov-maxim/OdataToEntity/blob/master/source/OdataToEntity.EfCore/OeEfCoreDataAdapter.cs#L35) class.

**Comment by voronov-maxim** [comment]
![image](https://user-images.githubusercontent.com/6085035/40922134-1af653b6-681a-11e8-8388-86c7ca76478f.png)

This is new class in ef core 2.1. Try run 'dotnet build' from console.
I clone repository from scratch and build succeded.

**Comment by techniq** [comment]
Awe, sorry I hadn't moved to 2.1 just yet (the OData hurdle was the last one, hence using your library).  I'm still digging into #16 (and more generally, getting my full DbContext to not throw exceptions on startup).  Once I get it going, I plan to jump to 2.1.

Thanks for the quick response.
