### ISSUE TITLE
Support DbContext with DbContextOptions<TDbContext> options and multi-parameter constructors

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#26]
It is [recommended](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#constructor-argument) (and in some cases needed) to use the generic `DbContextOptions<TDbContext>` and not just `DbContextOptions`, and is what we use in our project.

I've temporarily worked around the issue by taking in the non-generic version, but it would be nice to get around this issue:

"The DbContext of type 'MyCommonDbContext' cannot be pooled because it does not have a single public constructor accepting a single parameter of type DbContextOptions."

![image](https://user-images.githubusercontent.com/177476/44149487-4d0456b8-a06a-11e8-8987-2c0100ca1a2e.png)

Also, our `CommonDbContext` constructor requires a `ILogger` instance as the second parameter, which complicates things with the way OdataToEntity uses pooling.  To workaround this, I subclass `CommonDbContext` as `MyCommonDbContext` and create the logger myself, instead of having it dependency injected.

```c#
public class FinanceDbDataAdapter : OeEfCoreDataAdapter<MyCommonDbContext>
{
    public FinanceDbDataAdapter(DbContextOptions<MyCommonDbContext> options) : base(options, new OeQueryCache(false))
    {
    }
}

public class MyCommonDbContext : CommonDbContext
{
        public MyCommonDbContext(DbContextOptions<CommonDbContext> options) : base(options, new LoggerFactory().CreateLogger<MyCommonDbContext>())
    {
    }
}
```

It would be great if I didn't have to do that and instead could just use

```c#
public class FinanceDbDataAdapter : OeEfCoreDataAdapter<CommonDbContext>
{
    public FinanceDbDataAdapter(DbContextOptions<CommonDbContext> options) : base(options, new OeQueryCache(false))
    {
    }
}
```

These might be helpful
- https://github.com/aspnet/EntityFrameworkCore/pull/9465
- https://github.com/aspnet/EntityFrameworkCore/issues/9433

**Comment by voronov-maxim** [comment]
You can override OeEfCoreDataAdapter.CreateDataContext()

**Comment by techniq** [comment]
@voronov-maxim That looks like it could do the trick.  I should be able to DI my `CommonDbContext` instance and return it within `OeEfCoreDataAdapter.CreateDataContext()`


I've switched back to my other branch (based on OData/WebApi) and need to push for a release, but I'll give this a shot when I get some time and re-open if I have any issues.  Thanks again.

**Comment by techniq** [comment]
@voronov-maxim this so far has been working for me (leaving here in case others run into the issue).

```c#
using System;
using Microsoft.EntityFrameworkCore;
using OdataToEntity.Cache;
using OdataToEntity.EfCore;

namespace Finance.Data
{
    public class FinanceDbDataAdapter : OeEfCoreDataAdapter<FinanceDbContext>
    {
        public IServiceProvider ServiceProvider { get; set; }

        public FinanceDbDataAdapter(IServiceProvider serviceProvider) : base(null, new OeQueryCache(false))
        {
            this.ServiceProvider = serviceProvider;
        }

        public override object CreateDataContext()
        {
            return ServiceProvider.GetService(typeof(FinanceDbContext));
        }

        public override void CloseDataContext(Object dataContext)
        {
            // Handled by DI
        }
    }
}
```
