### ISSUE TITLE
Support for inline counts (?$count=true)

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#30]
> The $count system query option ignores any $top, $skip, or $expand query options, and returns the total count of results across all pages including only those results matching any specified $filter and $search

Will include `"@odata.count": {NUMBER},` in the response with the total number of entries across all pages (taking into affect the `$filter`) which is really useful for paginated interfaces (data tables, etc).  Implementations I've seen have been to issue a second `select count(*) ...` query.

Specification: [11.2.5.5 System Query Option $count](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc445374632)

Example: https://services.odata.org/Experimental/Northwind/Northwind.svc/Customers?$count=true&$top=5

**Comment by voronov-maxim** [comment]
[CountExpandNested](https://github.com/voronov-maxim/OdataToEntity/blob/b55608ab0588b5bd1011d16005973c383cd7c088/test/OdataToEntity.Test/Common/SelectTest2.cs#L17)
[CountQueryParameter](https://github.com/voronov-maxim/OdataToEntity/blob/b55608ab0588b5bd1011d16005973c383cd7c088/test/OdataToEntity.Test/Common/SelectTest2.cs#L45)
[CountQueryParameterFilter](https://github.com/voronov-maxim/OdataToEntity/blob/b55608ab0588b5bd1011d16005973c383cd7c088/test/OdataToEntity.Test/Common/SelectTest2.cs#L67)

**Comment by techniq** [comment]
Hmm... when calling one of the [Test Controllers](https://github.com/voronov-maxim/OdataToEntity/tree/master/test/OdataToEntity.Test.Asp/OdataToEntity.Test.AspMvcServer/Controllers) I do not get the `@odata.count` in the response.

![image](https://user-images.githubusercontent.com/177476/51116713-e216d500-17d9-11e9-92f3-1f3e7a46ce3c.png)

**Comment by techniq** [comment]
I believe the issue is the expectation of a `OeAsyncEnumerator` [here](https://github.com/voronov-maxim/OdataToEntity/blob/master/source/OdataToEntity.AspNetCore/OeAspQueryParser.cs#L140)

![image](https://user-images.githubusercontent.com/177476/51117198-150d9880-17db-11e9-8d77-2a1ba8d3a09d.png)
