### ISSUE TITLE
Support selecting [NotMapped] properties

### ISSUE THREAD

**Issue by techniq** [voronov-maxim/OdataToEntity#31]
Currently if a property is marked with `[NotMapped]` it is not being returned by default, and if it's requested explicitly `$select=MyNotMappedProperty` it throws `Could not find a property named 'MyNotMappedProperty' on type 'MyClass'`.

I have used `[NotMapped]` to provide some server generated (non-persisted) properties in my current models.  For example:
```c#
public class MyClass
{
    // ...
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }

    [NotMapped]
    public string FullName { get { return @"{FirstName} {MiddleName} {LastName}"; } }
}
```

**Comment by voronov-maxim** [comment]
Generated expression tree must be translate into valid sql.
Instead use 
> $compute=concat(concat(concat(concat(FirstName,' '),MiddleName),' '),LastName) as FullName
