### ISSUE TITLE
Hide a property

### ISSUE THREAD

**Issue by LucaGabi** [voronov-maxim/OdataToEntity#35]
Hi,
    Can an object property be hidden form the result ?
Is this the way to do it ?
```
    .Select(SelectExpandType.Disabled, "Id", "OrderId");
```

**Comment by voronov-maxim** [comment]
https://github.com/voronov-maxim/OdataToEntity/wiki/Model-Bound-Attributes

**Comment by LucaGabi** [comment]
Can you write a small example ?

**Comment by voronov-maxim** [comment]
https://github.com/voronov-maxim/Doctors/commit/9d77887fdc5b6518e9dae7a57c0bc89e5221165a

**Comment by LucaGabi** [comment]
Thanks, I'll look.
