### ISSUE TITLE
How to expose metadata?

### ISSUE THREAD

**Issue by LucaGabi** [voronov-maxim/OdataToEntity#36]
Hi,

    Is there a way to expose metadata ?

**Comment by voronov-maxim** [comment]
Hi, [Wiki](https://github.com/voronov-maxim/OdataToEntity/wiki/Asp-.net-core)

[With controller](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test.Asp/OdataToEntity.Test.AspMvcServer/Controllers/MetadataController.cs)
[Without controller](https://github.com/voronov-maxim/OdataToEntity/blob/d422c998073872cc274933d743f72e16ffdb61bc/source/OdataToEntity.AspNetCore/OeMiddleware.cs#L43)

**Comment by LucaGabi** [comment]
Thanks!
