### ISSUE TITLE
How do I use DynamicDataAdapter?

### ISSUE THREAD

**Issue by duynii** [voronov-maxim/OdataToEntity#38]
Hi can you update Readme.md on the latest DynamicDataAdapter please.

You can also email me at duytng@gmail.com.

I am also having problem with $orderBy after an aggregation:
http://dummy/odata/Books?$apply=groupby((Author), aggregate(Price with sum as Total)&$orderby=Total

I can only orderby for actual attribute on Book entity.

**Comment by voronov-maxim** [comment]
Dynamic data context not ready yet, working in progress.
```cs
var stream = new MemoryStream();

var optionsBuilder = new DbContextOptionsBuilder<DynamicDbContext>();
optionsBuilder = optionsBuilder.UseSqlServer(@"Server=.\sqlexpress;Initial Catalog=OdataToEntity;Trusted_Connection=Yes;", opt => opt.UseRelationalNulls(true));
var sqlServerSchema = new SqlServerSchema(optionsBuilder.Options);
var metadataProvider = new DynamicMetadataProvider(sqlServerSchema);
//metadataProvider.TableMappings = GetMappings();

var typeDefinitionManager = DynamicTypeDefinitionManager.Create(metadataProvider);
var dataAdapter = new DynamicDataAdapter(typeDefinitionManager);
var dynamicEdmModel = dataAdapter.BuildEdmModel();

var parser = new OeParser(new Uri("http://dummy"), dynamicEdmModel);
await parser.ExecuteGetAsync(new Uri("http://dummy/Orders?$expand=Customer,Items&$orderby=Id"), OeRequestHeaders.JsonDefault, stream, CancellationToken.None);

stream.Position = 0;
String result = new StreamReader(stream).ReadToEnd();
```

Error ordering an aggregation result, this is bug Microsoft.OData.Core
[filter and orderby on aggregation result do not work](https://github.com/OData/odata.net/issues/703)

**Comment by duynii** [comment]
Hi

I found something else interesting. The issue is not present in the Webapi sample for .NET or .NET Core inmemory data store. This indicates that it is not a problem in the ODataUriParser class - core.

I did a small project to test this out and have managed to reproduced the problem.
An exception is thrown when your call ODataUriParser.ParseUri() method. You can get it to work by calling ParseApply() first.

When I added this into your OeParser.cs, I am getting other errors in your orderby parsing code.
It complain about converting `SingleValueOpenPropertyAccessNode` to `SingleValuePropertyAccessNode`. In your code it assumes the orderbyClause.Expression is always a `SingleValuePropertyAccessNode`

Is it possible to fix this? (This is just a guess)

`public static ODataPath ParsePath(IEdmModel edmModel, Uri serviceRoot, Uri uri)
        {
            var uriParser = new ODataUriParser(edmModel, serviceRoot, uri, ServiceProviderImpl.Instance);
            uriParser.ParseApply();
            return uriParser.ParsePath();
        }
        public static ODataUri ParseUri(IEdmModel edmModel, Uri relativeUri)
        {
            var uriParser = new ODataUriParser(edmModel, relativeUri, ServiceProviderImpl.Instance);
            uriParser.ParseApply();
            return uriParser.ParseUri();
        }
        public static ODataUri ParseUri(IEdmModel edmModel, Uri serviceRoot, Uri uri)
        {
            var uriParser = new ODataUriParser(edmModel, serviceRoot, uri, ServiceProviderImpl.Instance);
            uriParser.ParseApply();
            return uriParser.ParseUri();
        }
`

**Comment by voronov-maxim** [comment]
Hi

Thanks for investigation how to fix bug

**Comment by duynii** [comment]
Thanks for fixing this.

I have a console application that builds the EDM and connects using EF Core. It takes 1.7s for the first query and ~ 100ms for subsequence queries. I assume it is loading the DLLs and taking a long time. 

In your opinion is there a way to rebuild the EDM and controller class in a MVC application? I also need OData support (not just return the entire entityset or one entity as some online examples shows).

**Comment by voronov-maxim** [comment]
[Try warm up](https://andrewlock.net/reducing-latency-by-pre-building-singletons-in-asp-net-core/)
