### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by duynii** [voronov-maxim/OdataToEntity#39]
Hi

The Pagination according to the wiki does not work. I set it to paginate on size 4.
https://github.com/voronov-maxim/OdataToEntity/wiki/Server-Driven-Paging

This is how I create the dataAdapter (I also tried to use its default constructor). I had to delete the default constructor for connection pooling.
`var optionsBuilder = new DbContextOptionsBuilder<odataContext>();
            
optionsBuilder = optionsBuilder.UseNpgsql(connStringLocal);
            var dataAdapter = new OeEfCoreDataAdapter<odataContext>(optionsBuilder.Options)
            {
                 IsDatabaseNullHighestValue = true //PostgreSql
            };`

**Comment by voronov-maxim** [comment]
Hi, please send minimal code reproducing pagination bug
