### ISSUE TITLE
Question : configuring logging does not seem to work ?

### ISSUE THREAD

**Issue by StefH** [voronov-maxim/OdataToEntity#41]
When adding this code for EnableSensitiveDataLogging and custom loggerfactory, there is still no logging visible in the console when running the api.

``` c#
var dbLoggerFactory = LoggerFactory.Create(builder =>
            {
                builder
                    .AddFilter("Default", LogLevel.Debug)
                    .AddFilter("Microsoft", LogLevel.Information)
                    //.AddFilter("System", LogLevel.Information)
                    .AddDebug()
                    .AddConsole();
            });

            var optionsBuilder = new DbContextOptionsBuilder<NorthwindContext>();
            optionsBuilder.UseLoggerFactory(dbLoggerFactory); // Warning: Do not create a new ILoggerFactory instance each time
            optionsBuilder.UseSqlServer(Configuration.GetConnectionString("NorthwindContext"), opt => opt.UseRelationalNulls());
            optionsBuilder.EnableSensitiveDataLogging();
            optionsBuilder.EnableDetailedErrors();

            var dataAdapter = new NorthwindDataAdapter(optionsBuilder.Options, true);
            services.AddOdataToEntityMvc(dataAdapter.BuildEdmModelFromEfCoreModel());
```

Project : https://github.com/StefH/ODataToEntityExampleWebApi/tree/master/ODataToEntityExampleWebApi

**Comment by voronov-maxim** [comment]
[AspMvcServer](https://github.com/voronov-maxim/OdataToEntity/tree/master/test/OdataToEntity.Test.Asp/OdataToEntity.Test.AspMvcServer) write to console
![console](https://user-images.githubusercontent.com/6085035/75526094-2ab34100-5a22-11ea-962a-7c51a19ec2fb.png)

**Comment by StefH** [comment]
The normal logging seems to work, but I want to see logging from the generated SQL code.

I tried adding the logging to the `OnConfiguring` from the context, but that fails with a ...pooling.. exception. See my NorthwindContext.cs file for the full error.

**Comment by voronov-maxim** [comment]
add to ODataToEntityExampleWebApi.csproj
```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
```
![debug](https://user-images.githubusercontent.com/6085035/75533116-9054fc80-5a25-11ea-8921-2dc940cc0231.png)

**Comment by StefH** [comment]
Sorry, this does not help.


![image](https://user-images.githubusercontent.com/249938/75535696-8a571f80-5a15-11ea-81e3-4a13b735155f.png)

**Comment by voronov-maxim** [comment]
When I run your project
![console](https://user-images.githubusercontent.com/6085035/75536922-1d4c8580-5a27-11ea-85e0-f9b16c1bf088.png)

Remove all breakpoints

**Comment by StefH** [comment]
I had some other logging defines in my development.settings, so I removed these. However I get more debug logging from the whole project; Except from the SQL commands ?

**Comment by voronov-maxim** [comment]
https://www.entityframeworktutorial.net/efcore/logging-in-entityframework-core.aspx
https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging

**Comment by StefH** [comment]
I think the problem is that you don't copy some values like LoggerFactory when creating a new Options object.

## Start : logger is specified
![image](https://user-images.githubusercontent.com/249938/75542034-4bc66280-5a1f-11ea-8569-be46bf72b039.png)

## End : Logger is null
![image](https://user-images.githubusercontent.com/249938/75542053-52ed7080-5a1f-11ea-9d27-3ef72cf4e468.png)

**Comment by StefH** [comment]
The fix could be:
``` c#
if (coreOptionsExtension.ReplacedServices != null)
{
    CoreOptionsExtension newCoreOptions = contextOptions.GetExtension<CoreOptionsExtension>();
    foreach (KeyValuePair<Type, Type> replacedService in coreOptionsExtension.ReplacedServices)
        newCoreOptions = newCoreOptions.WithReplacedService(replacedService.Key, replacedService.Value);
    contextOptions = contextOptions.WithExtension(newCoreOptions);
}
else
{
    contextOptions = contextOptions.WithExtension(coreOptionsExtension); // Fix
}
```

**Comment by StefH** [comment]
When will you release a new NuGet?

**Comment by voronov-maxim** [comment]
https://www.nuget.org/packages/OdataToEntity.EfCore/2.5.0.1
