### ISSUE TITLE
Custom ControllerModelConvention to support 'normal' api controller actions?

### ISSUE THREAD

**Issue by StefH** [voronov-maxim/OdataToEntity#42]
I want to support 'normal' api controller actions like:

- `/Employees/1` --> return a single employee with id  = 1
- `/Employees/1,2,3` --> return a multiple employees with ids  = 1, 2 and 3

To get this working, I need to add something to `HttpGet("")` and probably need a custom ControllerModelConvention (which should be loaded before your conventions) to support this.

Can you help me?

**Comment by voronov-maxim** [comment]
> https://localhost:5001/Employees?ids=1&ids=2&ids=3

```cs
        [HttpGet]
        public IAsyncEnumerable<Employee> Get([FromQuery(Name = "ids")] int[] ids)
```
Or use OData [in operator](https://github.com/voronov-maxim/OdataToEntity/blob/4e150bc34949f596fc90cc37c9e6ed1d3f16e322/test/OdataToEntity.Test/Common/SelectTest.cs#L858)

**Comment by voronov-maxim** [comment]
Hi @StefH 
You write pre-employment tests?

**Comment by StefH** [comment]
What do you mean?

**Comment by voronov-maxim** [comment]
Looks like this is your first ASP MVC project.

**Comment by StefH** [comment]
Ah I see.
Not really my first one, just investigating if mixing your OData logic with normal api controllers does work and could be used in our project because that project is now using the OData extensions from microsoft for efcore3.x which has still some issues, like expanding multiple sub-entities.
