### ISSUE TITLE
OeMiddleware - does support POST / PATCH / DELETE ?

### ISSUE THREAD

**Issue by ignatandrei** [voronov-maxim/OdataToEntity#47]
I have tried to create a new entity with Dynamic Data from connection string -
app.UseOdataToEntityMiddleware<OePageMiddleware>("/odata", edmModel);

and shows data as it was a GET , not a POST .

Apparently, from the code in 
`public class OeMiddleware
public async Task Invoke(HttpContext httpContext)
private async Task InvokeApi(HttpContext httpContext)`

it calls always GET , not POST.

There is a 
parser.ExecutePostAsync
but it is not called. And , when I try to call POST , verifies if it is batch or OperationImportSegment , then it call anyway the ExecuteQueryAsync
  
OeMiddleware - support POST / PATCH / DELETE ?

**Comment by voronov-maxim** [comment]
[Test](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test/Common/BatchTest.cs)
[Test data](https://github.com/voronov-maxim/OdataToEntity/tree/master/test/OdataToEntity.Test/Batches)
[Doc](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793748)
[Via controller](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test.Asp/OdataToEntity.Test.AspMvcServer/Controllers/OrdersController.cs)

**Comment by ignatandrei** [comment]
I have tried - with no luck. Working example: 

I have http://netcoreblockly.herokuapp.com/odata/$metadata

You can see the classRooms at GET:
http://netcoreblockly.herokuapp.com/odata/ClassRoom

I tried to POST ( with PostMan) to the endpoint:

http://netcoreblockly.herokuapp.com/odata/ClassRoom
The following:
 {
            "Name": "Classdasds1",
            "idClassRoom": 10
        }

It answers as the GET .

it is necessary , for the POST to work, to have a schema ?
(my code is: edmModel = DynamicMiddlewareHelper.CreateEdmModel(providerSchema, informationSchemaMapping: null); )

**Comment by voronov-maxim** [comment]
I will try to implement this on the weekend

**Comment by voronov-maxim** [comment]
![image](https://user-images.githubusercontent.com/6085035/82736608-c5769f80-9d33-11ea-96ed-0b2618396348.png)

**Comment by ignatandrei** [comment]
Thanks! Could you deploy on NuGet also  ?

**Comment by voronov-maxim** [comment]
Hi @ignatandrei 
[2.5.0.2](https://www.nuget.org/packages/OdataToEntity.EfCore.DynamicDataContext/)

**Comment by ignatandrei** [comment]
I have a problem with DELETE
It does not Delete ( verb: delete) Could you please verify?
Thanks again

**Comment by ignatandrei** [comment]
As an example:
GET - http://netcoreblockly.herokuapp.com/odatadb/ClassRoom(23) 
works

PATCH- http://netcoreblockly.herokuapp.com/odatadb/ClassRoom(23) 
BODY:
{
	
	"Name":"testAndrei
}
works

DELETE- http://netcoreblockly.herokuapp.com/odatadb/ClassRoom(23) 
does NOT work

( you could see the database connection string that I send over email)

This is reproducible in SqlServer and MySql. Could you please see ?

Thanks
Andrei

**Comment by voronov-maxim** [comment]
will fix it on the weekend

**Comment by ignatandrei** [comment]
Please deploy on nuget

**Comment by voronov-maxim** [comment]
[OdataToEntity.AspNetCore 2.5.0.3](https://www.nuget.org/packages/OdataToEntity.AspNetCore/)

**Comment by ignatandrei** [comment]
This package depends on 
https://www.nuget.org/packages/OdataToEntity/ 
version 2.5.0.3 - that was not deployed. 
So I cannot update reference.
Please deploy also OdataToEntity

**Comment by ignatandrei** [comment]
It works!
Thanks!
( With your software , we can now edit any SqlServer / MySql / PostGres ) if provided a connection string. - and I will put on Blockly)
