### ISSUE TITLE
OdataToEntity.EfCore.DynamicDataContext, DynamicTypeDefinitionManager and LRU caching

### ISSUE THREAD

**Issue by dshalkhakov** [voronov-maxim/OdataToEntity#50]
Hi,

I'm here to pitch an idea for an improvement.
So, we're using DynamicDataContext and we quickly ran into 'DynamicDbContext  out of range' exception.

We kind of resolved this problem by generating DynamicDbContexts and DynamicTypes at runtime in TypeResolve AppDomain event.

The next improvement would be to keep generated types in LRU cache, to keep memory usage constant.

Thoughts?

Cheers,
Dmitry

**Comment by voronov-maxim** [comment]
You can show example code  in TypeResolve method?

**Comment by dshalkhakov** [comment]
Somewhere early in program startup, and done exactly once:

`System.AppDomain.CurrentDomain.TypeResolve += HandleTypeResolve`

Then the `HandleTypeResolve` will be called when `DynamicTypeDefinitionManager` looks for a db context type using `Type.GetType` and doesn't find it.

And in `HandleTypeResolve` we'll look up the type in cache, generate it if needed, and then return it, like so (in pseudocode):

<pre>private System.Reflection.Assembly HandleTypeResolve(object sender, System.ResolveEventArgs args)
{
    if (_dynamicTypeService.IsDynamicContext(args.Name))
    {
        return _dynamicTypeService.GetOrCreateDynamicContext(args.Name);
    }
    return null;
}</pre>

But the problem remains that the `DynamicTypeDefinitionManager` [1] is implemented in such a way that new types need to be generated  over and over again and never be disposed of/re-used.

How about introducing
1. dynamic type generation instead of [2][3]
2. LRU cache for said `DynamicTypeDefinitionManager`?

[1] https://github.com/voronov-maxim/OdataToEntity/blob/addf0b4d76fcbf2f008b96590087a81c24c75485/source/OdataToEntity.EfCore.DynamicDataContext/DynamicTypeDefinitionManager.cs#L22
[2] https://github.com/voronov-maxim/OdataToEntity/blob/master/source/OdataToEntity.EfCore.DynamicDataContext/Types/DynamicDbContexts.cs
[3] https://github.com/voronov-maxim/OdataToEntity/blob/master/source/OdataToEntity.EfCore.DynamicDataContext/Types/DynamicTypes.cs

EDIT: formatting

**Comment by voronov-maxim** [comment]
Hi @dshalkhakov!

https://github.com/voronov-maxim/OdataToEntity/blob/ce85dec402790b4b1c8bc1b7028a48b3d10b21ce/test/OdataToEntity.Test.DynamicDataContext.AspServer/Startup.cs#L73
must be
```cs
IEdmModel edmModel = DynamicMiddlewareHelper.CreateEdmModelViaEmit(providerSchema, informationSchemaSettings);
```

**Comment by dshalkhakov** [comment]
Hi @voronov-maxim. I've looked into that method and the commit it appears in. It looks like it'd do the trick.
I wonder why it hasn't been released yet. Any reasons?

**Comment by dshalkhakov** [comment]
I've also looked into the current source [1][2] and it seems DynamicDbContexts are still not generated dynamically. A custom EmitDynamicTypeDefinitionManagerFactory might rectify that.

[1] https://github.com/voronov-maxim/OdataToEntity/blob/ce85dec402790b4b1c8bc1b7028a48b3d10b21ce/source/OdataToEntity.EfCore.DynamicDataContext/EmitDynamicTypeDefinitionManager.cs#L13
[2] https://github.com/voronov-maxim/OdataToEntity/blob/ce85dec402790b4b1c8bc1b7028a48b3d10b21ce/source/OdataToEntity.EfCore.DynamicDataContext/DynamicTypeDefinitionManagerFactory.cs#L18

**Comment by voronov-maxim** [comment]
Release [nuget 2.6.1](https://www.nuget.org/packages/OdataToEntity/)

To create a DynamicDbContext, an emit constructor is required. I do not see the need for this since only one context is used by default. Several contexts are used for xunit tests.
