### ISSUE TITLE
How change index in scheme for table with several indexes?

### ISSUE THREAD

**Issue by spot62** [voronov-maxim/OdataToEntity#52]
i have a mssql table with two indexes id and guid

```
CREATE TABLE [dbo].[myproducts](
	[guid] [uniqueidentifier] NOT NULL,
	[id] [int] NOT NULL,
	[name] [varchar](50) NULL,
	[cost] [money] NULL,
	[start_time] [smalldatetime] NULL,
 CONSTRAINT [PK_myproducts] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [guid_construint] UNIQUE NONCLUSTERED 
(
	[guid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
``` 

and OdataToEntity.Test.DynamicDataContext.AspServer.exe generates the scheme:
```
...
<Key>
  <PropertyRef Name="id"/>
</Key>
<Property Name="id" Type="Edm.Int32" Nullable="false"/>
<Property Name="cost" Type="Edm.Decimal"/>
<Property Name="guid" Type="Edm.Guid" Nullable="false"/>
<Property Name="name" Type="Edm.String"/>
<Property Name="start_time" Type="Edm.DateTimeOffset"/>

...
</edmx:Edmx>
```

How do i determine the index 'guid' instead index 'id' by dataschema? Is it possible?
Or how do i patch code to add such functionality yourself?

Thank you.

**Comment by voronov-maxim** [comment]
What problem do you want to solve?
$expand queries depend on the primary key type.

**Comment by spot62** [comment]
for above example , 'id' is index of remote system, and 'guid' is index of target system.
The remote system integrates with the target system through OData with 'guid' index (PropertyRef Name="guid")
Or i do need use views instead tables, with determining index too.

**Comment by voronov-maxim** [comment]
What problem do you want to solve?

OData can define [alternate key](http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part2-url-conventions/odata-v4.01-csprd05-part2-url-conventions.html#_Toc14103622)

**Comment by spot62** [comment]
I can not change a requests format in target system. It is a proprietary system with OData import.

**Comment by voronov-maxim** [comment]
You can:
1. Generate model from database [by example](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli).
2. Remove property "id" from "myproducts" class, mark "guid" KeyAttribute.
3. Create Asp server [by example](https://github.com/voronov-maxim/OdataToEntity/tree/master/test/OdataToEntity.Test.Asp/OdataToEntity.Test.AspServer).

**Comment by spot62** [comment]
Ok. Thank you.
