### ISSUE TITLE
Can you add support INSERT/UPDATE hierarchical data?

### ISSUE THREAD

**Issue by Makarov628** [voronov-maxim/OdataToEntity#54]
You've solved problem #53, thanks. Can you add support of inserting and updating hierarchical data? Or suggest how i can use your library to insert / update hierarchical data. 

You can use this repository as an example.
https://github.com/Makarov628/ODataToEntity_WebAPI

**Comment by voronov-maxim** [comment]
OdataToEnitys support [batch requests](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793748).
[Batch tests](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test/Common/BatchTest.cs).
[Test data](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test/Batches/Add.batch).
