### ISSUE TITLE
Why OdataToEntity was migrated to NET5?

### ISSUE THREAD

**Issue by rpokrovskij** [voronov-maxim/OdataToEntity#56]
This is only the question from developer to developer. 
What was the reason to migrate OdataToEntity from netstandard2.1 to net5.0 ?
I mean do you obtain any advantages in net5.0 that was not available on netstandard2.1 ?

**Comment by voronov-maxim** [comment]
While .NET Standard 2.1 will be the last version of .NET Standard, .NET 5 and all future versions will continue to support .NET Standard 2.1 and earlier. You should think of net5.0 (and future versions) as the foundation for sharing code moving forward.
EF Core 6.0 currently targets .NET 5. This will likely be updated to .NET 6 as we near the release. EF Core 6.0 does not target any .NET Standard version

**Comment by rpokrovskij** [comment]
OK.  If "EF Core 6.0 targets NET5" and you depends on it - this is ultimate reason.
