### ISSUE TITLE
An error occured while creating an instance of OeParser

### ISSUE THREAD

**Issue by DeshDeepakVerm** [voronov-maxim/OdataToEntity#58]
//Create adapter data access, where OrderContext your DbContext
var dataAdapter = new OeEfCoreDataAdapter<model.ordercontext>();
//Create query parser
var parser = new OeParser(new Uri("http://dummy"), dataAdapter, dataAdapter.BuildEdmModelFromEfCoreModel());--- Error here
//Query
var uri = new Uri("http://dummy/Orders?$select=Name");
//The result of the query
var response = new MemoryStream();
//Execute query
await parser.ExecuteGetAsync(uri, OeRequestHeaders.JsonDefault, response, CancellationToken.None);

We are getting below error:-

Method not found: 'System.Collections.Generic.IEnumerable`1<microsoft.entityframeworkcore.metadata .iproperty="">
Microsoft.EntityFrameworkCore.Metadata.Internal.
EntityTypeExtensions.GetDeclaredProperties
(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.

Please advise.

**Comment by voronov-maxim** [comment]
I cannot reproduce this issue.
Send me minimal solution for reproduce this issue and sql script for create schema.

**Comment by DeshDeepakVerm** [comment]
Hi Maxim , 

I am getting mentioned error in below line:

var parser = new OeParser(new Uri("http://dummy"), dataAdapter, dataAdapter.BuildEdmModelFromEfCoreModel());

Error is here : dataAdapter.BuildEdmModelFromEfCoreModel();

My project is built in .Net core 3.1 framework , I am working on official project so unable to send the code.

Thanks for understanding.
