### ISSUE TITLE
Throwing unhandled exception as package.

### ISSUE THREAD

**Issue by ccav01** [voronov-maxim/OdataToEntity#59]
When I use the nuget packages I get:  An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (ServiceProvider not found type Microsoft.OData.Json.IJsonWriterFactoryAsync)
OdataToEntity.Writers.OeGetWriter.SerializeAsync(OeQueryContext queryContext, IAsyncEnumerator<object> asyncEnumerator, string contentType, Stream stream, OeEntryFactory entryFactory, IServiceProvider serviceProvider, CancellationToken cancellationToken)

InvalidOperationException: ServiceProvider not found type Microsoft.OData.Json.IJsonWriterFactoryAsync
OdataToEntity.OeParser+ServiceProviderImpl.GetService(Type serviceType)

When I download source and include as project reference, it works fine.

Any ideas how to fix this?

**Comment by voronov-maxim** [comment]
Published version 2.8.0 https://www.nuget.org/packages/OdataToEntity/2.8.0
