### ISSUE TITLE
Add support count query option

### ISSUE THREAD

**Issue by genusP** [voronov-maxim/OdataToEntity#6]
Odata V4 support [$count query option](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752363) as analog $inlinecount in Odata V3.

PR #5 implement support this option

**Comment by voronov-maxim** [comment]
already supported, see xunit test SelectTest.Count "Orders/$count"

**Comment by genusP** [comment]
Support $count segment not query option.
Sample Usage http://services.odata.org/V4/(S(yfrvwjv1vbsg3w2g2cyyfc1h))/TripPinServiceRW/People?$expand=Friends($count=true;$select=FirstName;$top=2)&$select=FirstName&$count=true&$top=1&$skip=1

**Comment by voronov-maxim** [comment]
I spend refactoring your code, where necessary in my opinion
thanks for the help

**Comment by voronov-maxim** [comment]
@genusP 
#7 пофиксил с учетом фильров
