### ISSUE TITLE
$count option behaviour

### ISSUE THREAD

**Issue by Gorvat** [voronov-maxim/OdataToEntity#7]
Hi!
It is written in OData specification, that the $count system query option ignores any $top, $skip, or $expand query options, and returns the total count of results across all pages including only those results matching any specified $filter and $search
(http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_The_$inlinecount_System).
While testing OdataToEntity I noticed, that query like this (.../entity_name?count=true&$top=0) returns 0 in count, but it should return real count of entities, regardless $top option.
Please, fix $count behaviour according to specification.

**Comment by voronov-maxim** [comment]
https://github.com/voronov-maxim/OdataToEntity/commit/0f6a1d8bf02d69792625c3c563f2dd804bfaab7f
