### ISSUE TITLE
Remove or explain the dependency from Microsoft.EntityFrameworkCore.Relational 

### ISSUE THREAD

**Issue by rpokrovskij** [voronov-maxim/OdataToEntity#8]
I mean it should be possible to use / test OdataToEntity with InMemory database. 
May be it will be more clear for user to separate: OdataToEntity.EfCore and OdtatToEntity.EfCore.Relational

**Comment by voronov-maxim** [comment]
Microsoft.EntityFrameworkCore.Relational  used for execute stored procedures.
Project OdataToEntity.Test uses InMemory database provider for test.

**Comment by rpokrovskij** [comment]
What about splitting to two, OdataToEntity.EfCore and OdtatToEntity.EfCore.Relational ? I do not have strong arguments, just follow the EfCore logic: if EFCore authors split them then user libs should follow main road.

**Comment by voronov-maxim** [comment]
More abstractions to the god of abstractions. This will lead to the complicating of design and will not give advantages. Ef Core support Sql and NoSQL database.
