### ISSUE TITLE
Why OdataToEntity.EfCore depends on Standard 1.6 when Microsoft.EntityFrameworkCore by itself depends on Standard 1.3 ?

### ISSUE THREAD

**Issue by rpokrovskij** [voronov-maxim/OdataToEntity#9]
Why OdataToEntity.EfCore depends on Standard 1.6 Framework when EF Core by itself depends on Standard 1.3 ?
It is more logical to keep both on the same version (to be useful for all EF Core users). 

Even when my VS 2017 Class Standard Library framework is setuped to target Standard 1.6 (1.6.1 to be precise ) I got an error on adding Nuget package to it:

Restoring packages for D:\cot\DashboardCode\AdminkaV1\DataAccessEfCore.OdataToEntity\AdminkaV1.DataAccessEfCore.OdataToEntity.csproj...
  GET https://api.nuget.org/v3-flatcontainer/odatatoentity/index.json
  GET https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='OdataToEntity'
  OK https://api.nuget.org/v3-flatcontainer/odatatoentity/index.json 640ms
  GET https://api.nuget.org/v3-flatcontainer/odatatoentity/1.0.0.1/odatatoentity.1.0.0.1.nupkg
  OK https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='OdataToEntity' 765ms
  OK https://api.nuget.org/v3-flatcontainer/odatatoentity/1.0.0.1/odatatoentity.1.0.0.1.nupkg 758ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.odata.core/index.json
  GET https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.OData.Core'
  GET https://api.nuget.org/v3-flatcontainer/microsoft.odata.edm/index.json
  GET https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.OData.Edm'
  GET https://api.nuget.org/v3-flatcontainer/microsoft.spatial/index.json
  GET https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.Spatial'
  OK https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.OData.Core' 183ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.odata.core/index.json 628ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.odata.core/7.0.0/microsoft.odata.core.7.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.odata.edm/index.json 665ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.odata.edm/7.0.0/microsoft.odata.edm.7.0.0.nupkg
  OK https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.OData.Edm' 719ms
  OK https://ci.appveyor.com/nuget/nugetizer3000/FindPackagesById()?id='Microsoft.Spatial' 900ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.odata.core/7.0.0/microsoft.odata.core.7.0.0.nupkg 577ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.spatial/index.json 1261ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.spatial/7.0.0/microsoft.spatial.7.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.spatial/7.0.0/microsoft.spatial.7.0.0.nupkg 572ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.odata.edm/7.0.0/microsoft.odata.edm.7.0.0.nupkg 1451ms
Installing Microsoft.OData.Edm 7.0.0.
Installing Microsoft.Spatial 7.0.0.
Installing Microsoft.OData.Core 7.0.0.
Installing OdataToEntity 1.0.0.1.
***Package Microsoft.OData.Core 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.OData.Core 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
Package Microsoft.Spatial 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Spatial 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
Package Microsoft.OData.Edm 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.OData.Edm 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
One or more packages are incompatible with .NETStandard,Version=v1.6.***
Package restore failed. Rolling back package changes for 'AdminkaV1.DataAccessEfCore.OdataToEntity'.
Time Elapsed: 00:00:05.2998164

As a result OdataToEntity.EfCore nuget package was not added to the VS2017 project.

**Comment by voronov-maxim** [comment]
Workaround: Add the following property to the project 
`<PackageTargetFallback>dnxcore50;portable-net45+win8</PackageTargetFallback>`

**Comment by voronov-maxim** [comment]
reload nuget packages last version 1.1.1.1

**Comment by rpokrovskij** [comment]
Still not working... but with strange error at the end.

![image](https://user-images.githubusercontent.com/11598038/28866229-ed27d652-777a-11e7-91b7-56e3187cc82c.png)

**Comment by voronov-maxim** [comment]
I can not reproduce this error.
What the "displays dotnet" --version?
Try in project folder run  "dotnet restore"

**Comment by rpokrovskij** [comment]
dotnet --version returns 1.04 (referenced project version). 
when proj file of course contains `<TargetFramework>netstandard1.6</TargetFramework>`
dotnet restore or removing bin and obj folder doesn't help either. 
Seems like a VS bug.

Do you really have a strong reason to use Standard 1.06 for your library? I have stayed with 1.04 as I have met  less referencing problems with it and since future Standard 2.0 will target the same .NET Framework 4.6.1 (not 4.6.2 - which is target for Standard 1.6 )

![image](https://user-images.githubusercontent.com/11598038/28879079-d384c078-77a9-11e7-87ef-60deff7becb8.png)

**Comment by voronov-maxim** [comment]
I sync version odatatoentity with latest version entity framework core

**Comment by rpokrovskij** [comment]
Could I say something..
"to have a latest" is a good reason to keep user code upgraded but not good enough for library development. You limit library's usage to Standard 1.6 projects and didn't get anything instead. In case of Standard 1.6 it is wrong twice because Standard team were decided that moving  4.6.2 functionality to Standard and vNext by itself were errors and what they currently doing is "step back". This is my opinion of course, you can think different.
